# .pre-commit-config.yaml
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-yaml
      - id: check-added-large-files
      - id: end-of-file-fixer
      - id: trailing-whitespace

  # Ruff: Replaces Flake8, Isort, Black, and more with high speed
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.4.1
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format

  # Pytest: Using uv to run tests locally
  - repo: local
    hooks:
      - id: pytest-check
        name: pytest-check
        entry: uv run pytest
        language: system
        pass_filenames: false
        always_run: true
        stages: [push] # Optional: Only run on 'git push' to save time during commits